- hosts: masters
  become: yes
  gather_facts: false
  tasks:

    - name: get join command
      shell: kubeadm token create --print-join-command > /tmp/join-command
      changed_when: false
      tags: [ 'config' ]

    - name: copy join command to local file
      fetch:
        src: /tmp/join-command
        dest: /tmp/join-command
        flat: true
      tags: [ 'config' ]

- hosts: workers
  become: yes
  tasks:

    - name: stop firewall
      service:
        name: firewalld
        state: stopped
        enabled: false
      tags: [ 'system', 'firewall']

    - name: copy the join command to server location
      copy: src=/tmp/join-command dest=/tmp/join-command.sh mode=0777
      tags: [ 'config' ]

    - name: join the node to cluster
      command: sh /tmp/join-command.sh
      tags: [ 'config' ]
